//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dvs_ros_driver package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dvs_ros_driver__DVS_ROS_DRIVERCONFIG_H__
#define __dvs_ros_driver__DVS_ROS_DRIVERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dvs_ros_driver
{
  class DVS_ROS_DriverConfigStatics;

  class DVS_ROS_DriverConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(DVS_ROS_DriverConfig &config, const DVS_ROS_DriverConfig &max, const DVS_ROS_DriverConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const DVS_ROS_DriverConfig &config1, const DVS_ROS_DriverConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, DVS_ROS_DriverConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const DVS_ROS_DriverConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DVS_ROS_DriverConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const DVS_ROS_DriverConfig &config) const = 0;
      virtual void getValue(const DVS_ROS_DriverConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T DVS_ROS_DriverConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T DVS_ROS_DriverConfig::* field;

      virtual void clamp(DVS_ROS_DriverConfig &config, const DVS_ROS_DriverConfig &max, const DVS_ROS_DriverConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const DVS_ROS_DriverConfig &config1, const DVS_ROS_DriverConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, DVS_ROS_DriverConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const DVS_ROS_DriverConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DVS_ROS_DriverConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const DVS_ROS_DriverConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const DVS_ROS_DriverConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, DVS_ROS_DriverConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, DVS_ROS_DriverConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<DVS_ROS_DriverConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(DVS_ROS_DriverConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("streaming_rate"==(*_i)->name){streaming_rate = boost::any_cast<int>(val);}
        if("cas"==(*_i)->name){cas = boost::any_cast<int>(val);}
        if("injGnd"==(*_i)->name){injGnd = boost::any_cast<int>(val);}
        if("reqPd"==(*_i)->name){reqPd = boost::any_cast<int>(val);}
        if("puX"==(*_i)->name){puX = boost::any_cast<int>(val);}
        if("diffOff"==(*_i)->name){diffOff = boost::any_cast<int>(val);}
        if("req"==(*_i)->name){req = boost::any_cast<int>(val);}
        if("refr"==(*_i)->name){refr = boost::any_cast<int>(val);}
        if("puY"==(*_i)->name){puY = boost::any_cast<int>(val);}
        if("diffOn"==(*_i)->name){diffOn = boost::any_cast<int>(val);}
        if("diff"==(*_i)->name){diff = boost::any_cast<int>(val);}
        if("foll"==(*_i)->name){foll = boost::any_cast<int>(val);}
        if("Pr"==(*_i)->name){Pr = boost::any_cast<int>(val);}
      }
    }

    int streaming_rate;
int cas;
int injGnd;
int reqPd;
int puX;
int diffOff;
int req;
int refr;
int puY;
int diffOn;
int diff;
int foll;
int Pr;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int streaming_rate;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cas;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int injGnd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int reqPd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int puX;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int diffOff;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int refr;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int puY;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int diffOn;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int diff;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int foll;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Pr;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("DVS_ROS_DriverConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const DVS_ROS_DriverConfig &__max__ = __getMax__();
      const DVS_ROS_DriverConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const DVS_ROS_DriverConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const DVS_ROS_DriverConfig &__getDefault__();
    static const DVS_ROS_DriverConfig &__getMax__();
    static const DVS_ROS_DriverConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const DVS_ROS_DriverConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void DVS_ROS_DriverConfig::ParamDescription<std::string>::clamp(DVS_ROS_DriverConfig &config, const DVS_ROS_DriverConfig &max, const DVS_ROS_DriverConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class DVS_ROS_DriverConfigStatics
  {
    friend class DVS_ROS_DriverConfig;

    DVS_ROS_DriverConfigStatics()
    {
DVS_ROS_DriverConfig::GroupDescription<DVS_ROS_DriverConfig::DEFAULT, DVS_ROS_DriverConfig> Default("Default", "", 0, 0, true, &DVS_ROS_DriverConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.streaming_rate = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.streaming_rate = 10000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.streaming_rate = 30;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("streaming_rate", "int", 0, "integration time", "", &DVS_ROS_DriverConfig::streaming_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("streaming_rate", "int", 0, "integration time", "", &DVS_ROS_DriverConfig::streaming_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cas = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cas = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cas = 1992;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("cas", "int", 0, "cas (Photoreceptor cascode)", "", &DVS_ROS_DriverConfig::cas)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("cas", "int", 0, "cas (Photoreceptor cascode)", "", &DVS_ROS_DriverConfig::cas)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.injGnd = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.injGnd = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.injGnd = 1108364;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("injGnd", "int", 0, "injGnd (Differentiator switch level, higher to turn on more)", "", &DVS_ROS_DriverConfig::injGnd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("injGnd", "int", 0, "injGnd (Differentiator switch level, higher to turn on more)", "", &DVS_ROS_DriverConfig::injGnd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.reqPd = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.reqPd = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.reqPd = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("reqPd", "int", 0, "reqPd (AER request pulldown)", "", &DVS_ROS_DriverConfig::reqPd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("reqPd", "int", 0, "reqPd (AER request pulldown)", "", &DVS_ROS_DriverConfig::reqPd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.puX = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.puX = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.puX = 8159221;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("puX", "int", 0, "puX (2nd dimension AER static pullup)", "", &DVS_ROS_DriverConfig::puX)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("puX", "int", 0, "puX (2nd dimension AER static pullup)", "", &DVS_ROS_DriverConfig::puX)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.diffOff = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.diffOff = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.diffOff = 132;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("diffOff", "int", 0, "diffOff (OFF threshold, lower to raise threshold)", "", &DVS_ROS_DriverConfig::diffOff)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("diffOff", "int", 0, "diffOff (OFF threshold, lower to raise threshold)", "", &DVS_ROS_DriverConfig::diffOff)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.req = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.req = 309590;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("req", "int", 0, "req (OFF request inverter bias)", "", &DVS_ROS_DriverConfig::req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("req", "int", 0, "req (OFF request inverter bias)", "", &DVS_ROS_DriverConfig::req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.refr = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.refr = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.refr = 969;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("refr", "int", 0, "refr (Refractory period)", "", &DVS_ROS_DriverConfig::refr)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("refr", "int", 0, "refr (Refractory period)", "", &DVS_ROS_DriverConfig::refr)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.puY = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.puY = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.puY = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("puY", "int", 0, "puY (1st dimension AER static pullup)", "", &DVS_ROS_DriverConfig::puY)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("puY", "int", 0, "puY (1st dimension AER static pullup)", "", &DVS_ROS_DriverConfig::puY)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.diffOn = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.diffOn = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.diffOn = 209996;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("diffOn", "int", 0, "diffOn (ON threshold - higher to raise threshold)", "", &DVS_ROS_DriverConfig::diffOn)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("diffOn", "int", 0, "diffOn (ON threshold - higher to raise threshold)", "", &DVS_ROS_DriverConfig::diffOn)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.diff = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.diff = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.diff = 13125;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("diff", "int", 0, "diff (Differentiator)", "", &DVS_ROS_DriverConfig::diff)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("diff", "int", 0, "diff (Differentiator)", "", &DVS_ROS_DriverConfig::diff)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.foll = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.foll = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.foll = 271;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("foll", "int", 0, "foll (Src follower buffer between photoreceptor and differentiator)", "", &DVS_ROS_DriverConfig::foll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("foll", "int", 0, "foll (Src follower buffer between photoreceptor and differentiator)", "", &DVS_ROS_DriverConfig::foll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Pr = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Pr = 16777215;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Pr = 217;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("Pr", "int", 0, "Pr (Photoreceptor)", "", &DVS_ROS_DriverConfig::Pr)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr(new DVS_ROS_DriverConfig::ParamDescription<int>("Pr", "int", 0, "Pr (Photoreceptor)", "", &DVS_ROS_DriverConfig::Pr)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(DVS_ROS_DriverConfig::AbstractGroupDescriptionConstPtr(new DVS_ROS_DriverConfig::GroupDescription<DVS_ROS_DriverConfig::DEFAULT, DVS_ROS_DriverConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<DVS_ROS_DriverConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<DVS_ROS_DriverConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    DVS_ROS_DriverConfig __max__;
    DVS_ROS_DriverConfig __min__;
    DVS_ROS_DriverConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const DVS_ROS_DriverConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static DVS_ROS_DriverConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &DVS_ROS_DriverConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const DVS_ROS_DriverConfig &DVS_ROS_DriverConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const DVS_ROS_DriverConfig &DVS_ROS_DriverConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const DVS_ROS_DriverConfig &DVS_ROS_DriverConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<DVS_ROS_DriverConfig::AbstractParamDescriptionConstPtr> &DVS_ROS_DriverConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<DVS_ROS_DriverConfig::AbstractGroupDescriptionConstPtr> &DVS_ROS_DriverConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const DVS_ROS_DriverConfigStatics *DVS_ROS_DriverConfig::__get_statics__()
  {
    const static DVS_ROS_DriverConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = DVS_ROS_DriverConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DVS_ROS_DRIVERRECONFIGURATOR_H__
